---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cv.good-coffee-lover.io
  resources:
  - staticsites
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cv.good-coffee-lover.io
  resources:
  - staticsites/finalizers
  verbs:
  - update
- apiGroups:
  - cv.good-coffee-lover.io
  resources:
  - staticsites/status
  verbs:
  - get
  - patch
  - update
