# permissions for end users to view staticsites.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cv-operator
    app.kubernetes.io/managed-by: kustomize
  name: staticsite-viewer-role
rules:
- apiGroups:
  - cv.good-coffee-lover.io
  resources:
  - staticsites
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cv.good-coffee-lover.io
  resources:
  - staticsites/status
  verbs:
  - get
